[package]
name = "mempool"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
parity-scale-codec = {version = "2.3.1", features = ["derive", "chain-error"]}
serialization = { path = '../serialization' }
common = { path = '../common' }
anyhow = "1.0"
thiserror = "1.0"

[dev-dependencies]
rand = "0.8.4"
