[package]
name = "mempool"
version = "0.1.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
serialization = { path = '../serialization' }
subsystem = { path = '../subsystem' }
chainstate = { path = '../chainstate' }
common = { path = '../common' }
utils = { path = '../utils' }
logging = { path = '../logging' }
rpc = { path = '../rpc' }

anyhow = "1.0"
async-trait = "0.1"
futures = "0.3"
jsonrpsee = {version = "0.15", features = ["macros"]}
thiserror = "1.0"
lazy_static = "1.4"
mockall = "0.11.0"
parking_lot = "0.12"

[dev-dependencies]
chainstate-storage = { path = '../chainstate-storage' }

[dependencies.tokio]
version = "1"
default-features = false
features = ["io-util", "macros", "net", "rt", "rt-multi-thread", "sync", "time"]
